server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: "Prawko server"

  profiles:
    default: dev

  data:
    web:
      pageable:
        max-page-size: 100

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  jpa:
    open-in-view: false

  mail:
    properties:
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 10000
      "[mail.smtp.writetimeout]": 10000

password-reset:
  token-validity: 15m
  cooldown: 30m
