server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: "Prawko server"

  data:
    web:
      pageable:
        max-page-size: 100

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  datasource:
    url: jdbc:h2:mem:prawko
    username: sa
    password: ""
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    generate-ddl: true
    open-in-view: false
