server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: "Prawko server"

  profiles:
    default: dev

  data:
    web:
      pageable:
        max-page-size: 100

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  jpa:
    open-in-view: false
