cors:
  allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: never

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
