SET REFERENTIAL_INTEGRITY FALSE;

DELETE FROM question;
DELETE FROM exam;
DELETE FROM "user";
DELETE FROM role;

ALTER TABLE question ALTER COLUMN id RESTART WITH 1;
ALTER TABLE exam ALTER COLUMN id RESTART WITH 1;
ALTER TABLE "user" ALTER COLUMN id RESTART WITH 1;
ALTER TABLE role ALTER COLUMN id RESTART WITH 1;

INSERT INTO role (name) VALUES ('USER');
INSERT INTO role (name) VALUES ('ADMIN');

SET REFERENTIAL_INTEGRITY TRUE;